#!/usr/bin/env python3
"""
Setup script for the Synthesiser Backend
This script helps you create a .env file with the required API keys.
"""

import os
import sys

def create_env_file():
    """Create a .env file with the required environment variables."""
    
    print("🔧 Setting up environment variables for the Synthesiser Backend")
    print("=" * 60)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️  .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/N): ").lower().strip()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    print("\n📝 You need to provide the following API keys:")
    print("1. SupaData API Key - for YouTube transcript extraction")
    print("2. OpenAI API Key - for text summarization")
    print()
    
    # Get API keys from user
    supadata_key = input("Enter your SupaData API Key: ").strip()
    openai_key = input("Enter your OpenAI API Key: ").strip()
    
    if not supadata_key or not openai_key:
        print("❌ Both API keys are required!")
        return
    
    # Create .env file
    env_content = f"""# API Keys for the Synthesiser Backend
# Generated by setup_env.py

# SupaData API Key for YouTube transcript extraction
SUPADATA_API_KEY={supadata_key}

# OpenAI API Key for text summarization
OPENAI_API_KEY={openai_key}
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        print("\n✅ .env file created successfully!")
        print("📁 Location: Backend/.env")
        print("\n🚀 You can now start the backend server with:")
        print("   cd Backend")
        print("   python app.py")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

if __name__ == "__main__":
    create_env_file() 